language: c    #. Not really, it's actually bash

branches:
  only:
    - stable   #. stable (public) release
    - frozen   #. freeze point between stable and unstable
    - volatile #. short-lived but promising branches worth testing
    - unstable #. don't expect no history-rewrites here!

before_install:
  - sudo apt-get update -qq
  - share/unit/citm before_install

env:
  global:
    - SITE_PROFILE="TRAVIS"
    - PATH="${PATH}:${HOME}/bin"
  matrix:
    # CONTEXT=execute MODULE=tutorial #. nima/site#15
    # CONTEXT=execute MODULE=remote   #. nima/site#13
    # CONTEXT=execute MODULE=dns      #. nima/site#10
    - CONTEXT=execute MODULE=help     #. nima/site#19
    - CONTEXT=execute MODULE=tunnel   #. nima/site#18
    - CONTEXT=execute MODULE=git      #. nima/site#9
    - CONTEXT=execute MODULE=vault    #. nima/site#17
    - CONTEXT=execute MODULE=util     #. nima/site#4
    - CONTEXT=execute MODULE=gpg      #. nima/site#5
    - CONTEXT=execute MODULE=hgd      #. nima/site#3
    - CONTEXT=execute MODULE=net      #. nima/site#7
    - CONTEXT=installer MODULE=-

script:
  - share/unit/citm script
