language: c

branches:
  only:
    - stable   #. stable (public) release
    - frozen   #. freeze point between stable and unstable
    - volatile #. short-lived but promising branches worth testing
    - unstable #. don't expect no history-rewrites here!

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq make
  - sudo apt-get install -qq bash sed gawk git socat netcat gnupg2
  - sudo apt-get install -qq python python-virtualenv
  - sudo apt-get install -qq net-tools

env:
  global:
    - SITE_PROFILE="TRAVIS"
    - PATH="${PATH}:${HOME}/bin"

script:
  - make install       #. Test fresh install
  - make uninstall     #. Test uninstall
  - make install       #. Test reinstall
  - make purge         #. Test purge
  - make install       #  Install again now for unit-testing
  - site unit test hgd #. nima/site#3
  - site unit test gpg #. nima/site#5
  - site unit test net #. nima/site#7
